export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

export const VALIDATE_INPUT_SUCCESS = "VALIDATE_INPUT_SUCCESS";
export const VALIDATE_INPUT_FAILURE = "VALIDATE_INPUT_FAILURE";

export const FETCH_USER_DETAILS = "FETCH_USER_DETAILS";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

